title: Devin's Badges
logo: https://cdn.jsdelivr.net/npm/@intergrav/devins-badges@2/assets/branding/ghpages-banner_512w.png
description: Beautifully designed badges for many services.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme