title: Devin's Badges
logo: https://raw.githubusercontent.com/intergrav/devins-badges/v1/assets/db-assets/ghpages-banner_512w.png
description: Beautifully designed badges for many services.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
